opendatasoft/ods-dataviz-sdk

packages/api-client/.gitignore
packages/api-client/package.json
packages/api-client/src/client/index.ts
packages/api-client/tsdx.config.js

The goal of this PR is to be able to use the API Client in the ObservableHQ website. To do so, it is [necessary to propose a UMD bundle](https://observablehq.com/@observablehq/how-to-require-stubborn-modules).
I've made a test in ObservableHQ [here](https://observablehq.com/@wmai/testing-opentdatasoft-api-client). The bundles are exposed from my local environment using Ngrok.
I believe that it will be necessary to manually access the UMD bundle using the CDN **UNPKG** ([UNPKG `@opendatasoft/api-client`](https://unpkg.com/browse/@opendatasoft/api-client@0.0.2/)).
If we publish this version on npm, the right way to require the module on ObservableHQ will be:
```javascript
myModule = require(`(https://unpkg.com/browse/@opendatasoft/api-client@0.0.3/dist/umd/opendatasoft.apiclient.umd.js`) …
```

[ch26406] Feature: UMD bundle

---

packages/api-client/README.md
packages/api-client/tsdx.config.js

The example in the README.md of the Client API, we use the public domain, this is not reliable, we should use `documentation-resources` instead.
[This dataset](https://documentation-resources.opendatasoft.com/explore/dataset/doc-geonames-cities-5000/table/) seems to be a perfect fit.
Related ticket [here](https://app.clubhouse.io/opendatasoft/story/26407/as-a-developer-i-need-to-use-immutable-datasets-in-the-documentation-in-order-to-have-reliable-results).
The [CodeSandbox sample](https://codesandbox.io/s/api-clientget-started-be0xu?file=/src/index.js) has been updated as well.

[ch26407] Doc: use immutable dataset in documentation

---

packages/visualizations/src/components/Chart/Chart.svelte
packages/visualizations/src/components/types.ts

Since we support `aspectRatio` already, I added `maintainAspectRatio` in the same way.
This is very much passing straight ChartJS options, but I don't think it's too much of an issue considering all the drawing part is very much depending on ChartJS's specific implementation anyway; it seems alright to expose its properties straight away and rely on its official documentation on this part.

Support `maintainAspectRatio` in chart options

---

packages/visualizations-react/test/MarkdownText.test.tsx
packages/visualizations/src/components/MarkdownText/MarkdownText.svelte

This PR makes sure that if you pass MarkdownText content like this:
```
\*\*I shouldn't be bold!\*\*
\# I'm a hashtag, not a title
```
The characters are properly escaped and displayed, without showing the `\`, or interpreting the token as Markdown syntax.

fix(MarkdownText): Don't display escape characters

---

packages/visualizations/src/components/MarkdownText/MarkdownText.svelte

We only want to support tight lists, despite Markdown supporting both tight lists and loose lists.
This PR introduces a small plugin that makes it so MarkdownIt always renders tight lists, even if the initial parsing created a loose one (which is indicated by list items containing non-hidden paragraphs).

MarkdownText: Display all lists as tight lists

---

packages/visualizations-react/stories/Map/NonInteractiveChoropleth.stories.tsx
packages/visualizations-react/stories/Map/StudioChoropleth.stories.tsx
packages/visualizations/src/components/Map/Choropleth.svelte
packages/visualizations/src/components/Map/MapRender.svelte
packages/visualizations/src/components/Map/utils.js

The goal for this PR is to add an option for MapRender to enable or disable map interactivity.
Default value should be true as this is the default and normal MapLibre behaviour.
MapLibre gives an interesting option on map creation to easily disable map interactivity `interactive=false` that disables basic user interactions but it is not handling the navigation control panel and our added tooltips.
You can see a possible simple implementation in this [commit](https://github.com/opendatasoft/ods-dataviz-sdk/commit/0575bfb94194c75378eeadbeeb3822b3ea648e81)
The issue with this approach is that this option can't be changed afterwards and if you want to make the map interactive again you will have to create another one...
Finally I chose to handle interactivity both ways and allow a switch to …

Map option to disable interaction

---

package.json
packages/api-client/package.json
packages/visualizations-react/package-lock.json
packages/visualizations-react/package.json
packages/visualizations/package.json

This PR adds an npm script to rebuild package lock if they happen to not be in sync
With the new Lerna version, they are not rebuilt—which is great because they used to f* up the dff—and so can be out of sync with the package.json. Running the command will solve that.

chore: added a command to rebuild lock files

---

packages/visualizations-react/stories/Map/LegendLabelsRotation.stories.tsx
packages/visualizations-react/stories/Map/StudioChoropleth.stories.tsx
packages/visualizations-react/stories/Map/StudioChoroplethVector.stories.tsx
packages/visualizations-react/stories/Map/Tooltip.stories.tsx
packages/visualizations/src/components/Map/types.ts
packages/visualizations/src/components/Map/utils.ts

The goal for this PR is to rename the ambiguous `tooltip.labelFormatter` callback into `tooltip.formatter` which in fact can format the label AND the value for Choropleths tooltip.
_(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-37317](https://app.shortcut.com/opendatasoft/story/37317)._

Feat: Rename `tooltip.labelFormatter` callback into `tooltip.formatter` in Choropleths options

---

packages/visualizations-react/stories/Map/StudioChoroplethVector.stories.tsx
packages/visualizations/src/components/Map/WebGl/ChoroplethVectorTiles.svelte
packages/visualizations/src/components/Map/WebGl/MapRender.svelte
packages/visualizations/src/components/Map/types.ts

The goal for this PR is to fix two recent regressions : 
1) The resizer fits the map to the viewBox instead of the currentViewBox what produces a weird behaviour. If you select a map through navigation buttons, on resize it would take you back to default viewBox. Just replacing viewBox by the currentViewBox fixes that.
2) We removed setting the map max bounds from the resizer and as it is based on `map.getBounds()` after doing a first `fitBox(bbox)`, it causes a bad behaviour on resize and aspect ratio changes and sometimes constraining the map too much making it impossible to see everything.
The fix is to always set max bounds depending on the bbox or the currentBbox on each change, that way the map will be always limited even if you navigate through navigation buttons. It removes the …

Fix viewbox resizer not on currentViewBox and max bounds not refreshing

---

.github/workflows/chromatic.yml

The goal for this PR is to fix the chromatic Github action workflow that fails since last week 
See https://github.com/opendatasoft/ods-dataviz-sdk/actions/runs/4313418002
Defines the version of the node on which the workflow should run.

fix: node version for chromatic action

---

packages/visualizations/src/components/Map/WebGl/ChoroplethVectorTiles.svelte
packages/visualizations/src/components/Map/utils.ts

The goal for this PR is to use case-insensitive matching in Choropleth's shape filtering.
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-39521]
There are some counties (UK) where the administrative boundaries from our reference data contains uppercase alphanum characters (`E08000003`), but due to various technical reasons, it ends up passed as `e08000003`, so the matching doesn't work, and we filter everything out including the one thing we didn't want.
Considering solving the issue on the other end (platform) isn't realistic without adding an additional API call, and that there is 0 chance in real life that a shape identifier will mean different things with a different case, it seems reasonable to transform the matching to be case insensitive.
Adding `["get", key]` in …

Choropleth: Use case-insensitive matching for shape filtering

---

README.md
packages/api-client/README.md

The goal for this PR is to update some links related to the explore API
I removed the link to [API Client Reference](docs/modules.md) in `packages/api-client/README.md`
Is it related to something that has been deleted?

[CHORE][DOC] Edit and rename links to Explore APIv2

---

packages/api-client/src/client/types.ts
packages/visualizations-react/stories/Poi/PoiGeoJson.stories.tsx
packages/visualizations/src/components/MapPoi/PoiGeoJson.svelte
packages/visualizations/src/components/MapPoi/types.ts

The goal for this PR is to update `data` object to be consistent with other visualisation components and add `ApiExport` type to handle new typescript needs.

POI maps : update data object and add ApiExport type

---

lerna.json
packages/visualizations-react/stories/Chart/RadialCharts/RadialCharts.stories.tsx
packages/visualizations-react/stories/Chart/StudioLayouts/DoughnutChart.stories.tsx
packages/visualizations/src/components/Chart/Chart.svelte
packages/visualizations/src/components/Chart/datasets.ts
packages/visualizations/src/components/Chart/types.ts

The goal for this PR is to allow adding a cutout to Doughnut charts as a percentage string
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-42059](https://app.shortcut.com/opendatasoft/story/42059).
Adding a case handling where we check if `option` has a `cutout` property. We cannot use a type guard to check if we use a Doughnut chart because of a bug in ChartJS : https://github.com/chartjs/Chart.js/issues/10896#issuecomment-1660559770*/
Edit: Now we check if `chartType`is `Doughnut` so we can look for the series option `cutout` to put it in the `chartOptions`

feat: add-cutout-option-for-doughnut-charts

---

.github/pull_request_template.md
packages/api-client/README.md

The goal for this PR is to catch-up the merged "support record endpoint in api-client" PR (#183) with conventional commits.
I added a small bit of doc, which fits what currently exists in the README. It's starting to look a bit "light" if we consider this a doc, but we'll see that later.
I edited the PR template to mention conventional commits.
It would be nice indeed to only offer ODSQL features (`.where()`, `.limit()` etc) on endpoints that support it, but this doesn't seem trivial at all, especially if we want to do it right and really support the right parameters on each endpoint. I think it's firmly out of scope for this one.

feat: Add Record endpoint in api-client

---

packages/visualizations-react/stories/Chart/AxisAssemblages/AxisAssemblages.stories.tsx
packages/visualizations/src/components/Chart/datasets.ts
packages/visualizations/src/components/Chart/types.ts

The goal for this PR is to expose the `stack` property of Chart.js, to be able to configure [Bar and Column charts with groups](https://www.chartjs.org/docs/latest/samples/bar/stacked-groups.html). It also update storybook with demonstration stories.
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-43517](https://app.shortcut.com/opendatasoft/story/43517/sdk-expose-api-for-stacked-y-bar).
- Expose chart.js `stack` property for Bar charts.
- Update AxisAssemblages stories with stories for grouped bar and bar charts. 
none
In the Chart component, it is now possible to configure Bar and Column charts with groups using the `stack` property.
?
- No impact on existing bar and column charts
- works as expected

[sc-43517] Expose config for Bar and Column charts with groups

---

packages/visualizations-react/stories/Chart/AxisAssemblages/AxisAssemblages.stories.tsx
packages/visualizations/src/components/Chart/Chart.svelte
packages/visualizations/src/components/Chart/datasets.ts
packages/visualizations/src/components/Chart/scales.ts
packages/visualizations/src/components/Chart/types.ts
packages/visualizations/src/components/utils/formatter.ts

The goal for this PR is to add a new type of chart: [Scatter](https://www.chartjs.org/docs/latest/charts/scatter.html)
⚠️  **This is a very simple implementation, which forms the basis for iterating according to future needs.**
⚠️  Commits will be purged before merge
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-42061](https://app.shortcut.com/opendatasoft/story/42061).
- Update `NumericCartesianAxisConfiguration` types to allow linear Cartesian axis to begin at zero
**x and y axis doesn't begins at zero by default (so no breaking changes)**
- Handle the scatter case for tooltip and dataset builds
none
Add new chart type: scatter

[FEATURE][SC-42061] Add scatter chart

---

packages/visualizations/src/components/MapPoi/Map.ts
packages/visualizations/src/components/MapPoi/MapRender.svelte

The goal for this PR is to update the size of the map when its container changes
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-43538](https://app.shortcut.com/opendatasoft/story/43538).
Add a resize observer 
none
none
none
Inspect the HTML document with the id="map", change its width/height. Map should resize

[FIX][POI Maps]: add map resize observer

---

packages/visualizations-react/stories/Chart/AxisAssemblages/AxisAssemblages.stories.tsx
packages/visualizations/src/components/Chart/datasets.ts
packages/visualizations/src/components/Chart/types.ts

This pull request introduces several changes to the `visualizations-react` and `visualizations` packages, specifically targeting scatter plot chart configurations. The changes primarily focus on code refactoring and minor enhancements for better maintainability and flexibility.
Fixes the error on the platform:
```shell
Type '{ type: ChartSeriesType.Doughnut; cutout: string; valueColumn: string; label?: string | undefined; indexAxis: string; backgroundColor?: string | string[] | undefined; pointRadius?: number | undefined; pointHitRadius?: number | undefined; pointHoverRadius?: number | undefined; pointBorderColor?: string | undefined; d...' is not assignable to type 'ChartSeries'.
Type '{ type: ChartSeriesType.Doughnut; cutout: string; valueColumn: string; label?: string | undefined; …
```

fix: Use same typing for `indexAxis` as other charts series

---

packages/visualizations/src/components/MapPoi/Map.svelte
packages/visualizations/src/components/MapPoi/Map.ts
packages/visualizations/src/components/MapPoi/MapRender.svelte
packages/visualizations/src/components/MapPoi/constants.ts
packages/visualizations/src/components/MapPoi/types.ts
packages/visualizations/src/components/MapPoi/utils.ts
packages/visualizations/src/stores/createDeepEqual.ts

The goal for this PR is to add `zoom`and `center`in the options prop
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-43528](https://app.shortcut.com/opendatasoft/story/43528).
Fix a behavior where the map bbox was updated when a change in `options`. Did the same thing for the center prop.In `Map.svelte` the `bbox` and `center` given to `mapRender` change only their value change not their reference. 
Maybe we can factorize this code into something like` const freshCenter = useFreshValue(center, comparaisonCallback)`
none
/
/
/

[FEATURE][POI MAP] Add `zoom`and `center` options

---

packages/visualizations/src/components/MapPoi/Map.svelte
packages/visualizations/src/components/MapPoi/MapRender.svelte
packages/visualizations/src/components/MapPoi/types.ts
packages/visualizations/src/components/MapPoi/utils.ts

The goal for this PR is to add transform requests to style URLs passed to mapbox. Notably enables the use of mapbox styles (e.g. through the use of [a lib like this](https://www.npmjs.com/package/maplibregl-mapbox-request-transformer))
Add transform request parameters in all related components, down to `initializeMap`
I left the transform request "free form", so that the users can provide anything they want. But maybe, on top of that, we should add few commont providers internally, like mapbox or IGN.

add: transform request

---

packages/visualizations/src/components/MapPoi/Map.ts
packages/visualizations/src/components/MapPoi/constants.ts

The goal for this PR is to add a simple rule to make the clicked feature still visible when the sidebar popup is open. 
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-43611](https://app.shortcut.com/opendatasoft/story/43611).
If the popup is of type 'sidebar', the map will be centred on the element clicked, with a left margin of 300px.
As you can see in the video, we don't return to the initial center before clicking. 
IMO, this is still a good improvement and as the sidebar is probably going to be completely redesigned, it may not be worth spending any more time on it to try to going back to the original center.
https://github.com/opendatasoft/ods-dataviz-sdk/assets/117300300/22045473-425b-453c-96a9-e400721eab3f
/
/
/
/

[FIX][POI Map] Clicked feature is always visible when sidebar popup is open

---

packages/api-client/src/client/types.ts

The goal for this PR is to fix a mismatch between `Facet` type and the reality of what the API provides.
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-44362](https://app.shortcut.com/opendatasoft/story/44362/api-client-facet-typing-doesn-t-match-api-structure).
The changes are made to match the current structure of both facets endpoint in the API.
`Facet` types has been fixed to properly match Opendatasoft's API responses.
I added `state` as a very simple type without an enum. I don't think it's worth adding an enum here.

fix(api-client): Fix Facet types to match API v2.1

---

packages/visualizations/src/components/MapPoi/Map.ts
packages/visualizations/src/components/MapPoi/MapRender.svelte

The goal for this PR is to reset the bbox to its initial state when disabling map interactivity. 
https://github.com/opendatasoft/ods-dataviz-sdk/assets/84501475/941cfa8d-7bc8-4d85-9b05-b7783d56c7ed
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-44552](https://app.shortcut.com/opendatasoft/story/44552/studio-poi-maps-bbox-doesn-t-reset-when-the-block-is-deselected).
In MapPOI class we memoize the `bbox` passed to `setBbox` to be able to reset the bounds to the initial state in `toggleInteractivity`.
Should be none should only fit map to initial bounds when interactivity is disabled.
We fixed a bug in POI maps where the bbox was not reinitialized to initial bounds after disabling interactivity.
I had the choice between storing the initial `bbox` in the class `MapPOI` or …

Reset bbox to initial state when interactivity is disabled

---

packages/visualizations/src/components/MapPoi/Map.svelte

The goal for this PR is to destructure the style options, so that the reactive call is not triggered if `options` but not `options.style` changes.
Admittedly, `{#key …` and `$: …` seems to work differently on that matter.

fix: destructure style options

---

packages/visualizations-react/stories/Map/StudioChoropleth.stories.tsx
packages/visualizations-react/stories/Map/StudioChoroplethVector.stories.tsx
packages/visualizations-react/stories/Poi/PoiMap.stories.tsx
packages/visualizations/package-lock.json
packages/visualizations/package.json
packages/visualizations/src/components/Map/WebGl/ChoroplethGeoJson.svelte
packages/visualizations/src/components/Map/WebGl/ChoroplethVectorTiles.svelte
packages/visualizations/src/components/Map/WebGl/MapRender.svelte
packages/visualizations/src/components/Map/types.ts
packages/visualizations/src/components/Map/utils.ts
packages/visualizations/src/components/MapPoi/Map.svelte
packages/visualizations/src/components/MapPoi/MapRender.svelte
packages/visualizations/src/components/MapPoi/types.ts
packages/visualizations/src/components/MapPoi/utils.ts
packages/visualizations/src/components/types.ts

The goal for this PR is to add the option of cooperative gestures for maps, both POI and Choropleth.
This PR needs an update of Maplibre at least up to version 2.2.0 but as the version 2.2.1 fixes some typings issue on Maplibre expressions, it seems better to already update to 2.2.1.
I had troubles to fix the way we defined `FilterExpression`, If you see better solutions, please let me know ! And also this upgrade will have consequences for our users, some types changes will be necessary even if it doesn't appear heavy.
Please check if there is no regression due to the types changes (I've slightly changed the way the functions are made)
There is a change in Chromatic that I can't really explain: https://www.chromatic.com/test?appId=616594e84c1692003af430f3&id=655b8ed6701077f47cbd3365. It …

feat: add cooperative gestures for maps

---

packages/visualizations-react/stories/Poi/PoiMap.stories.tsx
packages/visualizations/src/components/Legend/CategoryLegend/Item/CategoryLegendItemSymbol.svelte
packages/visualizations/src/components/Legend/CategoryLegend/Symbols/ImageSymbol.svelte
packages/visualizations/src/components/Legend/types.ts

The goal for this PR is to add a new legend symbol in the legend.
Render an image as a legend item by providing an URL
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-44672](https://app.shortcut.com/opendatasoft/story/44672).
- A new legend item symbol: ImageSymbol
- Update POI map stories
_describe the changes that are not backward compatible_
Should we add the alt property ?  
Try to load large images to break the legend layout

[SC-44672][FEAT] Add new legend symbol: `Image`

---

packages/visualizations/src/components/MapPoi/Map.ts
packages/visualizations/src/components/MapPoi/constants.ts

This PR targets https://github.com/opendatasoft/ods-dataviz-sdk/pull/205. 
In https://github.com/opendatasoft/ods-dataviz-sdk/pull/205, the tooltip behavior changes a bit to adapt when the map width is small. In order catch any weird conflicts or behaviors that can arise, I decided not to start from `main` when creating this branch.
=> Didn't see anything weird
The goal for this PR is to fix the opening and closing mechanism for POI tooltip.
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-45182](https://app.shortcut.com/opendatasoft/story/45182).
https://github.com/opendatasoft/ods-dataviz-sdk/assets/117300300/53cdf037-a40a-4dc1-a7a2-178d4a8ccc49
- The main change is that we no longer depend on Maplibre to close the tooltip. (the popup option: `closeOnClick` is now …

[FIX][SC-45182]  Switch between tooltip should not require to close tooltip

---

packages/visualizations/src/components/Legend/CategoryLegend.svelte

The goal for this PR is to update the category legend css grid from 80 px to 120px (design request) Some changes will impact the graphs used by other teams but it appears that they follow the design changes.

chore: update category legend style grid to 120 px width

---

packages/visualizations-react/stories/Poi/PoiMap.stories.tsx
packages/visualizations-react/stories/Poi/sources.ts
packages/visualizations/src/components/Chart/Chart.svelte
packages/visualizations/src/components/Legend/CategoryLegend/Item/CategoryLegendItem.svelte
packages/visualizations/src/components/MapPoi/Map.svelte
packages/visualizations/src/components/MapPoi/Map.ts
packages/visualizations/src/components/MapPoi/MapRender.svelte
packages/visualizations/src/components/MapPoi/constants.ts
packages/visualizations/src/components/MapPoi/types.ts
packages/visualizations/src/components/MapPoi/utils.ts

~~The goal for this PR is to improve popup display on small screen.~~
~~The popup position is forced (take full width) when the map width is below 600px).~~
~~Also add a close icon button on popup (only for sidebar popup or when map size is below 600px)~~
The goal for this PR is to add a new popup display option: Modal
The popup takes the full width available. 
Popup height is based on its content with a `max-height` of `100%`
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-44895](https://app.shortcut.com/opendatasoft/story/44895). Can be tested with https://github.com/opendatasoft/platform/pull/11413
- Update Svelte to the last v3 version. ~~Need it to use CSS container queries. Support starts from v3.58.0~~
- Improve accessibility of legend items

[FEATURE][SC-44895][POI MAP] Popup improvements

---

packages/visualizations-react/stories/Poi/PoiMap.stories.tsx
packages/visualizations/src/components/MapPoi/Map.ts
packages/visualizations/src/components/MapPoi/types.ts

The goal for this PR is to support adding images to Maps for HDI displays
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-44585](https://app.shortcut.com/opendatasoft/story/44585).
Can be tested with https://github.com/opendatasoft/platform/pull/11458
Update the prop images to use [addImage](https://maplibre.org/maplibre-gl-js/docs/API/classes/maplibregl.Map/#addimage) options
This allow use to add images where their dimensions do not represent their final size in the map.
For example, In the platform, for Retina displays (pixelRatio: 2), marker images with icons are given to the map as 48x48 images, but they appear as 24x24 in the map.
|Before (blur images)|After|
|---|---|
|<img width="635" alt="Screenshot 2023-12-07 at 10 31 41" …

[POI MAPS] Add options for images

---

packages/visualizations/src/components/Map/WebGl/ChoroplethVectorTiles.svelte
packages/visualizations/src/components/Map/WebGl/MapRender.svelte
packages/visualizations/src/components/Map/types.ts

The goal for this PR is to add a props to override the default automatic max bounds computation. It seems that with very large bbox as for example the world bbox this automatic computation causes bad rendering depending on the canvas ratio. Overriding it with a new props is not the most satisfying solution but at this point I don't see another solution.
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-45683](https://app.shortcut.com/opendatasoft/story/45683/add-world-tileset-in-the-studio-choropleths).

feat: add fixed max bounds props

---

packages/visualizations/src/components/MapPoi/Map.ts
packages/visualizations/src/components/MapPoi/constants.ts

The goal for this PR is to add fullscreen controls to the POI maps
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-45176](https://app.shortcut.com/opendatasoft/story/45176).
https://github.com/opendatasoft/ods-dataviz-sdk/assets/117300300/11cf964f-3dce-4869-8d25-7c87087eb47b
Factorize functions to add / remove controls
Controls still react to the map interactivity and the active popup (if type is modal)
I didn't took the time to fit to the UI described in Zeplin where controls are in the same group.
**I took the short path where most of this feature is handled natively by Maplibre.**
To follow this Zeplin UI we need to [globally override how controls are created](https://docs.mapbox.com/mapbox-gl-js/api/markers/#icontrol) which can be time consuming. @benoitFortune I can …

[FEAT][POI Maps] Fullscreen control

---

packages/visualizations/src/components/Map/WebGl/MapRender.svelte

The goal for this PR is to harmonise the style of the cursor between all the SDK maps, to bring consistency to the use of the SDK.
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-45175](https://app.shortcut.com/opendatasoft/story/45175/sdk-choropleth-map-update-cursor-style).
Update pointer styles when it's over the map and when it's start to drag the map.
None...I hope
None
Always welcome
Simply test hovering and dragging a map in a studio page.

Increase style consistency on maps

---

.github/workflows/api-client.yml
.github/workflows/visualizations.yml

Last two commits in the main branch has no CI (https://github.com/opendatasoft/ods-dataviz-sdk/commits/main/).
The goal for this PR is to make Github actions run again on `main` branch
Update workflows triggers
_points that may not be obviously related to the changes but are impacted_
_special cases that are not widely known_

chore(CI): update github actions

---

packages/visualizations-react/stories/Poi/PoiMap.stories.tsx
packages/visualizations-react/stories/Poi/sources.ts
packages/visualizations/src/components/MapPoi/Map.ts
packages/visualizations/src/components/MapPoi/MapRender.svelte
packages/visualizations/src/components/MapPoi/constants.ts
packages/visualizations/src/components/MapPoi/utils.ts

The goal for this PR is ~~to test a simple implementation~~ to add navigation controls inside the popup when the click event query multiple features.
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-44648](https://app.shortcut.com/opendatasoft/story/44648/studio-poi-maps-navigate-through-records-in-the-tooltip).
https://github.com/opendatasoft/ods-dataviz-sdk/assets/117300300/6babce90-e045-4f6b-948c-4ea43b883fbf
Native Popup close button has been removed to add a custom arrow which is at the same level of the navigation buttons. 
We also update how a feature is highlight. Highlight and un-highlight strategies are different for each layer type. Currently, only 'symbol' and 'circle' has highlight and un-highlight strategies.
There is a small glitch when a symbol feature is …

feat(POI maps): add navigation controls for multi features popup

---

packages/visualizations/src/components/MapPoi/Map.ts
packages/visualizations/src/components/MapPoi/constants.ts
packages/visualizations/src/components/MapPoi/utils.ts

The goal for this PR is to prevent features in symbol layer to change of sort order. This result in a visual glitch where symbol feature change sort order when a feature is active (clicked)
Once we set a expression for the 'symbol-sort-key' property we need to reset the same expression. Otherwise sort order will change once the popup is removed. 
Link to the platform and create POI Maps with a large number of symbol

fix(POI Maps): prevent change in sort order for symbol features

---

packages/visualizations-react/stories/Table/Table.stories.tsx
packages/visualizations/src/components/Table/Cell/Format/DateFormat.svelte
packages/visualizations/src/components/Table/Cell/Format/NumberFormat.svelte
packages/visualizations/src/components/Table/Table.svelte
packages/visualizations/src/components/Table/store.ts
packages/visualizations/src/components/Table/types.ts

The goal for this PR is to add a locale prop to format numbers and dates
- New optionnal prop for the table: `locale`
- Add a context at the root of the table component. It's use a writable to store the current locale. Default value comes from `navigator.language`.

[FEAT][TABLE] Add locale options

---

packages/visualizations-react/.storybook/preview.js
packages/visualizations-react/.storybook/theme.css
packages/visualizations-react/jest.config.js
packages/visualizations-react/src/index.ts
packages/visualizations-react/stories/Table/Table.stories.tsx
packages/visualizations-react/stories/Table/custom-style.css
packages/visualizations-react/test/__mocks__/styleMock.js

The goal for this PR fix style missing in visualizations-react
React bundle import visualizations style. 
Storybook no longer need to import the visualizations style sheet

fix(style): import visualizations style in visualizations-react bundle

---

packages/visualizations/src/components/Map/WebGl/ChoroplethGeoJson.svelte
packages/visualizations/src/components/Map/WebGl/ChoroplethVectorTiles.svelte
packages/visualizations/src/components/Map/WebGl/MapRender.svelte
packages/visualizations/src/components/Map/types.ts
packages/visualizations/src/components/MapPoi/Map.svelte
packages/visualizations/src/components/MapPoi/MapRender.svelte
packages/visualizations/src/components/MapPoi/types.ts
packages/visualizations/src/components/MapPoi/utils.ts

The goal for this PR is to add the mapLibre `preserveDrawingBuffer` option to our maps components. This option enables the use of `toDataUrl`. This is needed to be able to export the map canvas to image formats.

feat: add preserveDrawingBuffer option to Maplibre maps

---

packages/visualizations-react/stories/Table/custom-style.css
packages/visualizations/src/components/Table/Headers/SortButton.svelte

The goal for this PR is to align number header right, wether they are sortable or not (design request) and to inherit color for the button—else the sortable field would not inherit theme color.

fix: align sort number right and color sort field

---

packages/visualizations/src/components/Pagination/PageSize.svelte

The goal for this PR is to fix the behavior for the page size select as it can't be used on Chrome/Safari
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-50479](https://app.shortcut.com/opendatasoft/story/50479).
Use the `input` event instead of the `select`. I didn't dive into the why, but it does the job.

[FIX][TABLE][SC-50479] Update page size

---

packages/visualizations/src/components/Pagination/PageSize.svelte

The goal for this PR is to remove safari glossy style on the page size select
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-50489](https://app.shortcut.com/opendatasoft/story/50489).
The solution is `-webkit-appearance: none` and readd the arrows as background image. The problem is, the background image is for all browsers, so we need to have `appearance: none;` globally.
This only applies to default style.
PageSize select doesn't have the default safari style anymore.

fix: remove safari select style

---

packages/visualizations-react/stories/Table/Table.stories.tsx
packages/visualizations/src/components/Table/Body.svelte
packages/visualizations/src/components/Table/Cell/Cell.svelte
packages/visualizations/src/components/Table/Cell/LoadingCell.svelte
packages/visualizations/src/components/Table/Cell/index.ts
packages/visualizations/src/components/Table/Table.svelte
packages/visualizations/src/components/Table/TableCard.svelte

The goal for this PR is to add a loading indicator in the rows, when `Table` awaiting new data. 
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-48032](https://app.shortcut.com/opendatasoft/story/48032/sdk-studio-implement-loading-records).
Add new subcomponent `LoadingCell` who is displayed when the property `isLoading` is true.
None
In the Table component a new svg is displayed when fetching the data.
There are 2 issues that I cannot resolve:
- the SVG is too high in the cell and I don't understand why
- the SVG is not displayed correctly in the different table cells (it only seems to fit the first cell)
New story in storybook

Loading records implementation

---

packages/visualizations/src/components/Table/Table.svelte

The goal for this PR is to add a scrollbox selector in order to override default styles (namely border radius in the Studio).
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-46294](https://app.shortcut.com/opendatasoft/story/46294).

chore: add scrollbox selector

---

package-lock.json
package.json
packages/visualizations-react/LICENSE
packages/visualizations-react/package.json
packages/visualizations/LICENSE
packages/visualizations/package.json
packages/visualizations/src/components/Chart/index.ts
packages/visualizations/src/components/Map/Svg/Map.svelte
packages/visualizations/src/index.ts

The goal for this PR is to export Svelte uncompiled components, so that they can be used **in a SvelteKit app**
I added a `svelte` field in package.json
`exports: { ".": { "import": …; "svelte": …; }` seems to confuse rollup and vite (contrary to what the doc suggests). It's be explored in further tests though, this is the right way to export both ESM and umd, something that has been troublesome.
The explicit import of `registerable` is to avoid tree shaking. I deleted the export the namespace since we actually don't use it, I don't think it had been tested that it worked and was messing up with explicit imports.
It's now possible to import svelte uncompiled components to be used in a Svelte app: 
```
<script>
import { Chart } from '@opendatasoft/visualizations';
</script>
<Chart {data} …
```

Export svelte uncompiled components

---

package-lock.json
packages/visualizations-react/package.json
packages/visualizations/package.json

The goal for this PR is to fix the dependency version of @opendatasoft/visualizations in visualizations-react that wasn't correctly updated due to a manual update of versions.

fix: upgrade linked version

---

packages/visualizations-react/stories/Table/Table.stories.tsx
packages/visualizations/src/components/Table/Body.svelte
packages/visualizations/src/components/Table/Table.svelte
packages/visualizations/src/components/Table/TableCard.svelte
packages/visualizations/src/components/Table/types.ts

The goal for this PR is to add a small phrase to indicate that no records were found—but appart from that the table hasn't crashed.
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-50771](https://app.shortcut.com/opendatasoft/story/50771).
I added another alternative render for the body, similar to the loading state.
I could have made it into it's own component, but I don't find the `Body.svelte` too cluttered for now. I'm totally open to it though.

feat: add an empty state for the table

---

packages/visualizations-react/stories/Poi/PoiMap.stories.tsx
packages/visualizations-react/stories/Poi/sources.ts
packages/visualizations-react/stories/Table/data.ts
packages/visualizations-react/stories/Table/options.ts
packages/visualizations/src/components/Map/WebGl/types.ts
packages/visualizations/src/components/Map/WebGl/utils.ts

The goal for this PR is to support fill layers in maps.
PoiMaps and table can renders maps with fill layers (geo shapes in our application)
https://github.com/opendatasoft/ods-dataviz-sdk/assets/117300300/a4815797-58d3-458c-99da-81936d4e9b98
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-46278](https://app.shortcut.com/opendatasoft/story/46278).
- Add new support layer: `fill`. Color is mandatory. Options are border color and opacity 
- Update a bit of PoiMap and Table stories

[FEAT][SC-46278] Support fill layers

---

packages/visualizations/src/components/Table/Body.svelte
packages/visualizations/src/components/Table/EmptyRow.svelte
packages/visualizations/src/components/Table/TableCard.svelte

The goal of this PR is to fix an issue where "no records" is not visible in a large table with a scroll section. Currently, having "no results" renders the table with a 'void' row, making it appear broken.
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-51257](https://app.shortcut.com/opendatasoft/story/51257).
Update the Empty part

[STYLE][TABLE]: "no records" label is always visible

---

packages/api-client/src/client/constants.ts

The goal for this PR is to add new dataset export formats
- geographic formats: fgb, gpx and parquet
- calendar format: ical
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-51661](https://app.shortcut.com/opendatasoft/story/51661).

[FIX][API-CLIENT] Update dataset exports formats

---

packages/visualizations/src/components/Table/Cell/Format/GeoFormat.svelte

The goal for this PR is to prevent Maplibre instances being created by merely passign the mouse over a cell (or tens of them if you pass your cursor through a page).
(Internal for Opendatasoft only) Associated Shortcut ticket: https://app.shortcut.com/opendatasoft/story/53245/table-don-t-create-the-map-immediately-on-hover
The map initialization was hooked to `onTrigger` which is defined as "Invoked once the tippy has been triggered by a DOM event (e.g. mouseenter).".
The PR uses `onShow`  instead ("Invoked once the tippy begins to show.") which takes the delay into account, so that you need to have the mouse over the cell for 500ms before Maplibre starts running.
Same logic for the map destruction which uses its mirror callback `onHide`.
Tippy doc: …

fix(Table): Delay map initialization to the tooltip creation

---

packages/visualizations-react/src/index.ts
packages/visualizations/src/components/Map/WebGl/types.ts

The goal for this PR is to expose the `Map/WebGl` component and required types through the `visualizations-react` package.
Since the component has a large value by itself, outside of its specialized `Poi` implementation, it makes sense to expose it as well. We're starting to use it natively in our platform.
None
The `WebGl` map component is now exported publicly from the `visualizations-react` package, as well as the types it requires for proper usage.

feat(WebGlMap): Export the component from the packages

---

packages/api-client/src/client/constants.ts
packages/api-client/src/client/types.ts

The goal for this PR is to add a new optional `semantic_type` property to dataset fields, to mirror this new feature in the API.
This new property is optional (the API only mentions it if it exists, otherwise it doesn't appear in the schema at all).
I added the two current values existing in the platform's backend.
None
In the API Client: The `DatasetField` type now includes the optional `semantic_type` which can be returned by the API for fields that are using a semantic type such as "IP Address". A semantic type is a higher-level type with specific behaviors.

feat(api-client): add semantic_type to DatasetField

---

packages/api-client/src/client/types.ts

The goal for this PR is to fix a sleeping typo in our `Dataset` type.
See https://public.opendatasoft.com/api/explore/v2.1/catalog/datasets/weatherref-france-vigilance-meteo-departement/
The correct term is `attachment`, not `attachement`.
I also renamed types that also used this term. 
I suppose worst case it will break broken things 🙈 
The property names and types related to "Attachements" are renamed to "Attachment" to match the API syntax and terms.

fix(api-client): Typo in attachment property name

---

packages/visualizations-react/stories/Table/Table.stories.tsx
packages/visualizations/src/components/Table/Body.svelte

The goal for this PR is to fix a case where loading cell would be misaligned with actual columns when a button column was present.
The cause is that we insert an extra column if `rowProps.onclick` is defined, but didin't do it on the loading part.
Add an empty cell with a min-width of 28px (button width) so that column count and alignment is preserved.
I added it to the loading story too to have a snapshot.

fix: add an empty column in loading cells too

---

packages/api-client/src/client/constants.ts
packages/api-client/src/client/types.ts
packages/api-client/src/odsql/index.ts
packages/api-client/test/odsql.test.ts

The goal for this PR is to add utils to the api client package
- Package has type and constant for metadata template field types
- Add a new ODSQL function lower
About the lower function.
I think we'll mostly use the combination `lower(field(' my field'))` when building queries
Do you see any reasons to not run the `field()` function inside `lower()` ?
We can't call `lower` inside `field` because it is not supported in every clause.
Other possibility would be to have optional arguments when calling `orderBy` or  `groupBy` to include the lower function but that requires to rewrite mostly all the logic of the Query class.

[API-CLIENT][FEAT] Add metadata template field type and ODSQL lower function

---

packages/visualizations-react/stories/Chart/TimeScale/ChartTimeScale.stories.tsx
packages/visualizations/src/components/Chart/scales.ts
packages/visualizations/src/components/Chart/types.ts

The goal for this PR is to improve the `TimeCartesianAxisConfiguration` type to add `TimeDisplayFormats`.
By exposing `TimeDisplayFormats`, we allow the modification of the display format of the labels on the graph axis.
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-55009](https://app.shortcut.com/opendatasoft/story/55009/as-a-user-i-want-to-display-my-data-results-by-weeks-time-scale).
Improve the type `TimeCartesianAxisConfiguration`.
In the Chart component: It's now possible to update the display for the x axis when the type is "time".

[FEAT][CHART] add TimeDisplayFormats for chart options

---

packages/visualizations-react/stories/Chart/TimeScale/ChartTimeScale.stories.tsx
packages/visualizations/src/components/Chart/scales.ts
packages/visualizations/src/components/Chart/types.ts

The goal for this PR is to control the date format displayed in Chart.js tooltips through a new property called `timeDisplayFormats`.
(Internal for Opendatasoft only) Associated Shortcut ticket: 🏴‍☠️
- new optional property `timeDisplayFormats` to the `TooltipConfiguration` interface.
- `scales.ts` use `timeDisplayFormats` property and prioritize it when formatting tooltip dates
- Fix storybook sample
None
In the Chart component: It's now possible to customize date formats in tooltips using the `timeDisplayFormats` property.
The implementation choice (`timeDisplayFormats`) is aligned with existing Chart.js conventions.
An alternative using functions (`dateFormatter`) was considered but postponed due to complexity in existing tooltip logic.
- Verify that custom date formats are correctly …

fix(Chart): allow customizing tooltip date formats

---

packages/visualizations-react/stories/Poi/PoiMap.stories.tsx
packages/visualizations-react/stories/Poi/sources.ts
packages/visualizations/src/components/Map/WebGl/types.ts
packages/visualizations/src/components/Map/WebGl/utils.ts

The goal for this PR is to draw lines layers on Webgl Maplibre maps
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-55946](https://app.shortcut.com/opendatasoft/story/55946).
- Update layers util to build line layers from props
- Update stories

[FEAT] Map -  support line layers

---

packages/api-client/src/client/constants.ts
packages/api-client/src/client/types.ts

The goal for this PR is to add a new type MetadataTemplateType and fix a const declaration for `ODS_METADATA_TEMPLATE_FIELD_TYPE`
(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-58684](https://app.shortcut.com/opendatasoft/story/58684).

[API-CLIENT][FIX] add type: `MetadataTemplateType`
